@RestApi_HostAddress = http://localhost:5555

### POST create delivery order
POST {{RestApi_HostAddress}}/api/warehouses
Content-Type: application/json

{
  "IdProduct": "The ID number of the product being delivered",
  "IdWarehouse": "The ID number of the warehouse realising the delivery",
  "Amount": "The amount of the product being delivered",
  "CreatedAt": "The time of creation of the delivery order"
}
